[package]
name = "precommit"
version = "0.1.0"
authors = ["rparki <chesslunatic@gmail.com>"]

[dependencies]
clap = { version = "~2.29.0", features = ["yaml"]}
git2 = "0.7"
regex = "1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"